import './globals.css'

import localFont from 'next/font/local'

const SatoshiFont = localFont({ src: './Satoshi-Variable.woff2', })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={SatoshiFont.className}>{children}</body>
    </html>
  )
}
