import './globals.css'

import localFont from 'next/font/local'

const SatoshiFont = localFont({ src: './Satoshi-Variable.woff2', })

import Script from "next/script";


export const metadata = {
  title: 'Abdul Moeez | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>

<Script
        strategy="lazyOnload"
        src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}
      />

<Script strategy="lazyOnload">
        {`
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {
                    page_path: window.location.pathname,
                    });
                `}
      </Script>




    <html lang="en">
      <body className={SatoshiFont.className}>{children}</body>
    </html>
  
  </>
  
  
  )
}
